{% set name = "ja-webutils" %}
{% set version = "0.1.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ja_webutils-{{ version }}.tar.gz
  sha256: 3f4aaba3faf0a6e419bd24cdc1ce1efa6892f79b5aa0cf14ed242ac2fbd4268e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61
    - setuptools-scm >=3.4.3
    - wheel
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - ja_webutils
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://git.ligo.org/joseph-areeda/ja_webutils
  dev_url: https://git.ligo.org/joseph-areeda/ja_webutils.git
  doc_url: https://joseph-areeda.docs.ligo.org/ja_webutils/
  summary: A python package to support HTML generation
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE.txt
  description: A pure Python class library to facilitate programatic generation of web pages. Three main classes
    Page - represents the full HTML. PageItem - an abstract base class for most non-form tags. 
    PageFormItem - an abstract base class for tags that return information.

extra:
  recipe-maintainers:
    - areeda
