{% set name = "ja-webutils" %}
{% set version = "0.1.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ja_webutils-{{ version }}.tar.gz
  sha256: 92be9fc2b162a3de9c1f2e1bbb11371146746c7964f64785d0661fa146b8686b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=61
    - setuptools-scm >=3.4.3
    - wheel
    - pip
  run:
    - python >=3.9

test:
  imports:
    - ja_webutils
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://git.ligo.org/joseph-areeda/ja_webutils
  dev_url: https://git.ligo.org/joseph-areeda/ja_webutils.git
  doc_url: https://joseph-areeda.docs.ligo.org/ja_webutils/
  summary: A python package to support HTML generation
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE.txt
  description: A pure Python class library to facilitate programatic generation of web pages. Three main classes
    Page - represents the full HTML. PageItem - an abstract base class for most non-form tags. 
    PageFormItem - an abstract base class for tags that return information.

extra:
  recipe-maintainers:
    - areeda
